### ISSUE TITLE
Bug: Fails to parse files with the "Comment" field set.

### ISSUE THREAD

**Issue by AsbjornOlling** [zsau/id3#3]
I tried parsing an mp3 file that I set the id3 `comment` field on, (set using the cli tool id3v2).

It did this:
```
lydbog.core=> (with-mp3 [mp3 "test.mp3"] (:id3/tag mp3))
Execution error (IllegalArgumentException) at id3/full->normal$fn (id3.clj:77).
No matching clause: :id3.frame.type/blob
```

I've found a different way to solve my problem, I think - just thought you might want to know about this failure mode :)

**Comment by zsau** [comment]
Apologies for the late response. This was fixed in #2, but I hadn't released a new version. I've switched the installation instructions to use `deps.edn` so you should be able to use the fix right away if you're using Deps. I'm not planning to keep releasing on Clojars unless there's demand for it, so let me know if you want that.
